import 'food.dart';

List<Food> burger = [
  Food(img: "assets/images/1.jpg", name: "Lorem Ipsum", price: 5, description: "distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a moredistracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more"),
  Food(img: "assets/images/2.jpg", name: "Lorem Ipsum", price: 7, description: "distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a moredistracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more"),
  Food(img: "assets/images/3.png", name: "Lorem Ipsum", price: 8, description: "distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a moredistracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more"),
  Food(img: "assets/images/4.jpg", name: "Lorem Ipsum", price: 4, description: "distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a moredistracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more"),
  Food(img: "assets/images/5.jpg", name: "Lorem Ipsum", price: 5, description: "distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a moredistracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more"),
  Food(img: "assets/images/6.jpeg", name: "Lorem Ipsum", price: 8, description: "distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a moredistracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more"),
  Food(img: "assets/images/7.jpg", name: "Lorem Ipsum", price: 6, description: "distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a moredistracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more"),
];